# Generated by Django 5.2.10 on 2026-01-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='searched_at',
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='pressure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
